/**
 * Generate .claude/settings.json based on installed skills and options
 */

/**
 * Generate settings.json content
 *
 * @param {string[]} skills - Array of skill IDs that were installed
 * @param {Object} options - Installation options
 * @param {boolean} options.hooks - Whether hooks were installed
 * @param {boolean} options.toon - Whether TOON utils were installed
 * @returns {string} JSON string for settings.json
 */
export function generateSettings(skills, options = {}) {
  const settings = {
    "$schema": "https://code.claude.com/schemas/settings.schema.json",
    "version": "1.0.0",
    "description": "Claude Code configuration - auto-generated by create-claude-starter"
  };

  // Add hooks configuration if hooks were installed
  if (options.hooks) {
    settings.hooks = {
      "pre-tool": {
        "enabled": false,
        "scripts": []
      },
      "post-tool": {
        "enabled": false,
        "scripts": []
      }
    };

    settings.description += " (hooks disabled by default - see .claude/hooks/README.md to enable)";
  }

  // Add skill-specific settings
  if (skills.length > 0) {
    settings.skills = {};

    skills.forEach(skillId => {
      settings.skills[skillId] = {
        enabled: true,
        model: "sonnet" // Default model for all skills
      };
    });
  }

  // Add TOON-specific settings if TOON utils were installed
  if (options.toon) {
    settings.toon = {
      enabled: true,
      binaryPath: ".claude/utils/toon/bin",
      autoDetect: true,
      description: "TOON format provides 30-60% token savings on tabular data"
    };
  }

  return JSON.stringify(settings, null, 2);
}

/**
 * Generate settings.local.json template
 * (For user-specific overrides that shouldn't be committed)
 */
export function generateLocalSettings() {
  const localSettings = {
    "$schema": "https://code.claude.com/schemas/settings.schema.json",
    "description": "Local overrides - add to .gitignore",
    "hooks": {
      "pre-tool": {
        "enabled": false
      }
    }
  };

  return JSON.stringify(localSettings, null, 2);
}

/**
 * Generate example settings with comments
 */
export function generateExampleSettings() {
  return `{
  "$schema": "https://code.claude.com/schemas/settings.schema.json",

  // Skills - auto-activated based on conversation context
  "skills": {
    "stripe": {
      "enabled": true,
      "model": "sonnet"  // Use "opus" for more complex tasks
    }
  },

  // Hooks - automation scripts (disabled by default)
  "hooks": {
    "pre-tool": {
      "enabled": false,
      "scripts": [
        // ".claude/hooks/secret-scanner.sh",
        // ".claude/hooks/toon-validator.sh"
      ]
    },
    "post-tool": {
      "enabled": false,
      "scripts": []
    }
  },

  // TOON format - token optimization
  "toon": {
    "enabled": true,
    "binaryPath": ".claude/utils/toon/bin",
    "autoDetect": true
  }
}`;
}

/**
 * Merge settings with existing settings.json if it exists
 *
 * @param {Object} existingSettings - Parsed existing settings.json
 * @param {Object} newSettings - New settings to merge
 * @returns {Object} Merged settings
 */
export function mergeSettings(existingSettings, newSettings) {
  return {
    ...existingSettings,
    ...newSettings,
    skills: {
      ...existingSettings.skills,
      ...newSettings.skills
    },
    hooks: newSettings.hooks || existingSettings.hooks,
    toon: newSettings.toon || existingSettings.toon
  };
}
